/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteRouteImport } from './routes/tutor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TutorSessionsRouteImport } from './routes/tutor/sessions'
import { Route as TutorSchedulesRouteImport } from './routes/tutor/schedules'
import { Route as TutorRegisterGenerationRouteImport } from './routes/tutor/register-generation'
import { Route as TutorNotesRouteImport } from './routes/tutor/notes'
import { Route as TutorMessagingRouteImport } from './routes/tutor/messaging'
import { Route as StudentCheckInRouteImport } from './routes/student/check-in'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoverPasswordRouteImport } from './routes/auth/recover-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as TutorClaimsIndexRouteImport } from './routes/tutor/claims.index'
import { Route as TutorClaimsClaimIdRouteImport } from './routes/tutor/claims.$claimId'

const TutorRouteRoute = TutorRouteRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TutorSessionsRoute = TutorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorSchedulesRoute = TutorSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorRegisterGenerationRoute = TutorRegisterGenerationRouteImport.update({
  id: '/register-generation',
  path: '/register-generation',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorNotesRoute = TutorNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorMessagingRoute = TutorMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => TutorRouteRoute,
} as any)
const StudentCheckInRoute = StudentCheckInRouteImport.update({
  id: '/student/check-in',
  path: '/student/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/auth/recover-password',
  path: '/auth/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorClaimsIndexRoute = TutorClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorClaimsClaimIdRoute = TutorClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => TutorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims/': typeof TutorClaimsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims': typeof TutorClaimsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims/': typeof TutorClaimsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/tutor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/register'
    | '/student/check-in'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin/'
    | '/settings/'
    | '/tutor/'
    | '/tutor/claims/$claimId'
    | '/tutor/claims/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/register'
    | '/student/check-in'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin'
    | '/settings'
    | '/tutor'
    | '/tutor/claims/$claimId'
    | '/tutor/claims'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/tutor'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/register'
    | '/student/check-in'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin/'
    | '/settings/'
    | '/tutor/'
    | '/tutor/claims/$claimId'
    | '/tutor/claims/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TutorRouteRoute: typeof TutorRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  StudentCheckInRoute: typeof StudentCheckInRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tutor/sessions': {
      id: '/tutor/sessions'
      path: '/sessions'
      fullPath: '/tutor/sessions'
      preLoaderRoute: typeof TutorSessionsRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/schedules': {
      id: '/tutor/schedules'
      path: '/schedules'
      fullPath: '/tutor/schedules'
      preLoaderRoute: typeof TutorSchedulesRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/register-generation': {
      id: '/tutor/register-generation'
      path: '/register-generation'
      fullPath: '/tutor/register-generation'
      preLoaderRoute: typeof TutorRegisterGenerationRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/notes': {
      id: '/tutor/notes'
      path: '/notes'
      fullPath: '/tutor/notes'
      preLoaderRoute: typeof TutorNotesRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/messaging': {
      id: '/tutor/messaging'
      path: '/messaging'
      fullPath: '/tutor/messaging'
      preLoaderRoute: typeof TutorMessagingRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/student/check-in': {
      id: '/student/check-in'
      path: '/student/check-in'
      fullPath: '/student/check-in'
      preLoaderRoute: typeof StudentCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/auth/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/claims/': {
      id: '/tutor/claims/'
      path: '/claims'
      fullPath: '/tutor/claims/'
      preLoaderRoute: typeof TutorClaimsIndexRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/claims/$claimId': {
      id: '/tutor/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/tutor/claims/$claimId'
      preLoaderRoute: typeof TutorClaimsClaimIdRouteImport
      parentRoute: typeof TutorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TutorRouteRouteChildren {
  TutorMessagingRoute: typeof TutorMessagingRoute
  TutorNotesRoute: typeof TutorNotesRoute
  TutorRegisterGenerationRoute: typeof TutorRegisterGenerationRoute
  TutorSchedulesRoute: typeof TutorSchedulesRoute
  TutorSessionsRoute: typeof TutorSessionsRoute
  TutorIndexRoute: typeof TutorIndexRoute
  TutorClaimsClaimIdRoute: typeof TutorClaimsClaimIdRoute
  TutorClaimsIndexRoute: typeof TutorClaimsIndexRoute
}

const TutorRouteRouteChildren: TutorRouteRouteChildren = {
  TutorMessagingRoute: TutorMessagingRoute,
  TutorNotesRoute: TutorNotesRoute,
  TutorRegisterGenerationRoute: TutorRegisterGenerationRoute,
  TutorSchedulesRoute: TutorSchedulesRoute,
  TutorSessionsRoute: TutorSessionsRoute,
  TutorIndexRoute: TutorIndexRoute,
  TutorClaimsClaimIdRoute: TutorClaimsClaimIdRoute,
  TutorClaimsIndexRoute: TutorClaimsIndexRoute,
}

const TutorRouteRouteWithChildren = TutorRouteRoute._addFileChildren(
  TutorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TutorRouteRoute: TutorRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  StudentCheckInRoute: StudentCheckInRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
