/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteRouteImport } from './routes/tutor/route'
import { Route as LecturerRouteRouteImport } from './routes/lecturer/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LecturerIndexRouteImport } from './routes/lecturer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TutorSessionsRouteImport } from './routes/tutor/sessions'
import { Route as TutorSchedulesRouteImport } from './routes/tutor/schedules'
import { Route as TutorRegisterGenerationRouteImport } from './routes/tutor/register-generation'
import { Route as TutorNotesRouteImport } from './routes/tutor/notes'
import { Route as TutorMessagingRouteImport } from './routes/tutor/messaging'
import { Route as TutorHelpRouteImport } from './routes/tutor/help'
import { Route as StudentCheckInRouteImport } from './routes/student/check-in'
import { Route as LecturerVerificationQueueRouteImport } from './routes/lecturer/verification-queue'
import { Route as LecturerTutorsRouteImport } from './routes/lecturer/tutors'
import { Route as LecturerSessionsRouteImport } from './routes/lecturer/sessions'
import { Route as LecturerScheduleRouteImport } from './routes/lecturer/schedule'
import { Route as LecturerReportsRouteImport } from './routes/lecturer/reports'
import { Route as LecturerMessagesRouteImport } from './routes/lecturer/messages'
import { Route as LecturerAttendanceRouteImport } from './routes/lecturer/attendance'
import { Route as LecturerAnalyticsRouteImport } from './routes/lecturer/analytics'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoverPasswordRouteImport } from './routes/auth/recover-password'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMessagingRouteImport } from './routes/admin/messaging'
import { Route as AdminInstitutionsRouteImport } from './routes/admin/institutions'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as TutorClaimsIndexRouteImport } from './routes/tutor/claims.index'
import { Route as TutorClaimsClaimIdRouteImport } from './routes/tutor/claims.$claimId'

const TutorRouteRoute = TutorRouteRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRouteRoute = LecturerRouteRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TutorSessionsRoute = TutorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorSchedulesRoute = TutorSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorRegisterGenerationRoute = TutorRegisterGenerationRouteImport.update({
  id: '/register-generation',
  path: '/register-generation',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorNotesRoute = TutorNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorMessagingRoute = TutorMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorHelpRoute = TutorHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => TutorRouteRoute,
} as any)
const StudentCheckInRoute = StudentCheckInRouteImport.update({
  id: '/student/check-in',
  path: '/student/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerVerificationQueueRoute =
  LecturerVerificationQueueRouteImport.update({
    id: '/verification-queue',
    path: '/verification-queue',
    getParentRoute: () => LecturerRouteRoute,
  } as any)
const LecturerTutorsRoute = LecturerTutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerSessionsRoute = LecturerSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerScheduleRoute = LecturerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerReportsRoute = LecturerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerMessagesRoute = LecturerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerAttendanceRoute = LecturerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const LecturerAnalyticsRoute = LecturerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LecturerRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/auth/recover-password',
  path: '/auth/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagingRoute = AdminMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstitutionsRoute = AdminInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TutorClaimsIndexRoute = TutorClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => TutorRouteRoute,
} as any)
const TutorClaimsClaimIdRoute = TutorClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => TutorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lecturer': typeof LecturerRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/lecturer/analytics': typeof LecturerAnalyticsRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/messages': typeof LecturerMessagesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/schedule': typeof LecturerScheduleRoute
  '/lecturer/sessions': typeof LecturerSessionsRoute
  '/lecturer/tutors': typeof LecturerTutorsRoute
  '/lecturer/verification-queue': typeof LecturerVerificationQueueRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/help': typeof TutorHelpRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims/': typeof TutorClaimsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/lecturer/analytics': typeof LecturerAnalyticsRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/messages': typeof LecturerMessagesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/schedule': typeof LecturerScheduleRoute
  '/lecturer/sessions': typeof LecturerSessionsRoute
  '/lecturer/tutors': typeof LecturerTutorsRoute
  '/lecturer/verification-queue': typeof LecturerVerificationQueueRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/help': typeof TutorHelpRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin': typeof AdminIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims': typeof TutorClaimsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/lecturer': typeof LecturerRouteRouteWithChildren
  '/tutor': typeof TutorRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/institutions': typeof AdminInstitutionsRoute
  '/admin/messaging': typeof AdminMessagingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/register': typeof AuthRegisterRoute
  '/lecturer/analytics': typeof LecturerAnalyticsRoute
  '/lecturer/attendance': typeof LecturerAttendanceRoute
  '/lecturer/messages': typeof LecturerMessagesRoute
  '/lecturer/reports': typeof LecturerReportsRoute
  '/lecturer/schedule': typeof LecturerScheduleRoute
  '/lecturer/sessions': typeof LecturerSessionsRoute
  '/lecturer/tutors': typeof LecturerTutorsRoute
  '/lecturer/verification-queue': typeof LecturerVerificationQueueRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/tutor/help': typeof TutorHelpRoute
  '/tutor/messaging': typeof TutorMessagingRoute
  '/tutor/notes': typeof TutorNotesRoute
  '/tutor/register-generation': typeof TutorRegisterGenerationRoute
  '/tutor/schedules': typeof TutorSchedulesRoute
  '/tutor/sessions': typeof TutorSessionsRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/claims/$claimId': typeof TutorClaimsClaimIdRoute
  '/tutor/claims/': typeof TutorClaimsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lecturer'
    | '/tutor'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/messaging'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/recover-password'
    | '/auth/register'
    | '/lecturer/analytics'
    | '/lecturer/attendance'
    | '/lecturer/messages'
    | '/lecturer/reports'
    | '/lecturer/schedule'
    | '/lecturer/sessions'
    | '/lecturer/tutors'
    | '/lecturer/verification-queue'
    | '/student/check-in'
    | '/tutor/help'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin/'
    | '/lecturer/'
    | '/settings/'
    | '/tutor/'
    | '/tutor/claims/$claimId'
    | '/tutor/claims/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/messaging'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/recover-password'
    | '/auth/register'
    | '/lecturer/analytics'
    | '/lecturer/attendance'
    | '/lecturer/messages'
    | '/lecturer/reports'
    | '/lecturer/schedule'
    | '/lecturer/sessions'
    | '/lecturer/tutors'
    | '/lecturer/verification-queue'
    | '/student/check-in'
    | '/tutor/help'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin'
    | '/lecturer'
    | '/settings'
    | '/tutor'
    | '/tutor/claims/$claimId'
    | '/tutor/claims'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lecturer'
    | '/tutor'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/institutions'
    | '/admin/messaging'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/recover-password'
    | '/auth/register'
    | '/lecturer/analytics'
    | '/lecturer/attendance'
    | '/lecturer/messages'
    | '/lecturer/reports'
    | '/lecturer/schedule'
    | '/lecturer/sessions'
    | '/lecturer/tutors'
    | '/lecturer/verification-queue'
    | '/student/check-in'
    | '/tutor/help'
    | '/tutor/messaging'
    | '/tutor/notes'
    | '/tutor/register-generation'
    | '/tutor/schedules'
    | '/tutor/sessions'
    | '/admin/'
    | '/lecturer/'
    | '/settings/'
    | '/tutor/'
    | '/tutor/claims/$claimId'
    | '/tutor/claims/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LecturerRouteRoute: typeof LecturerRouteRouteWithChildren
  TutorRouteRoute: typeof TutorRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  StudentCheckInRoute: typeof StudentCheckInRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tutor/sessions': {
      id: '/tutor/sessions'
      path: '/sessions'
      fullPath: '/tutor/sessions'
      preLoaderRoute: typeof TutorSessionsRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/schedules': {
      id: '/tutor/schedules'
      path: '/schedules'
      fullPath: '/tutor/schedules'
      preLoaderRoute: typeof TutorSchedulesRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/register-generation': {
      id: '/tutor/register-generation'
      path: '/register-generation'
      fullPath: '/tutor/register-generation'
      preLoaderRoute: typeof TutorRegisterGenerationRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/notes': {
      id: '/tutor/notes'
      path: '/notes'
      fullPath: '/tutor/notes'
      preLoaderRoute: typeof TutorNotesRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/messaging': {
      id: '/tutor/messaging'
      path: '/messaging'
      fullPath: '/tutor/messaging'
      preLoaderRoute: typeof TutorMessagingRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/help': {
      id: '/tutor/help'
      path: '/help'
      fullPath: '/tutor/help'
      preLoaderRoute: typeof TutorHelpRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/student/check-in': {
      id: '/student/check-in'
      path: '/student/check-in'
      fullPath: '/student/check-in'
      preLoaderRoute: typeof StudentCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/verification-queue': {
      id: '/lecturer/verification-queue'
      path: '/verification-queue'
      fullPath: '/lecturer/verification-queue'
      preLoaderRoute: typeof LecturerVerificationQueueRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/tutors': {
      id: '/lecturer/tutors'
      path: '/tutors'
      fullPath: '/lecturer/tutors'
      preLoaderRoute: typeof LecturerTutorsRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/sessions': {
      id: '/lecturer/sessions'
      path: '/sessions'
      fullPath: '/lecturer/sessions'
      preLoaderRoute: typeof LecturerSessionsRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/schedule': {
      id: '/lecturer/schedule'
      path: '/schedule'
      fullPath: '/lecturer/schedule'
      preLoaderRoute: typeof LecturerScheduleRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/reports': {
      id: '/lecturer/reports'
      path: '/reports'
      fullPath: '/lecturer/reports'
      preLoaderRoute: typeof LecturerReportsRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/messages': {
      id: '/lecturer/messages'
      path: '/messages'
      fullPath: '/lecturer/messages'
      preLoaderRoute: typeof LecturerMessagesRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/attendance': {
      id: '/lecturer/attendance'
      path: '/attendance'
      fullPath: '/lecturer/attendance'
      preLoaderRoute: typeof LecturerAttendanceRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/lecturer/analytics': {
      id: '/lecturer/analytics'
      path: '/analytics'
      fullPath: '/lecturer/analytics'
      preLoaderRoute: typeof LecturerAnalyticsRouteImport
      parentRoute: typeof LecturerRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/auth/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messaging': {
      id: '/admin/messaging'
      path: '/messaging'
      fullPath: '/admin/messaging'
      preLoaderRoute: typeof AdminMessagingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/institutions': {
      id: '/admin/institutions'
      path: '/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AdminInstitutionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tutor/claims/': {
      id: '/tutor/claims/'
      path: '/claims'
      fullPath: '/tutor/claims/'
      preLoaderRoute: typeof TutorClaimsIndexRouteImport
      parentRoute: typeof TutorRouteRoute
    }
    '/tutor/claims/$claimId': {
      id: '/tutor/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/tutor/claims/$claimId'
      preLoaderRoute: typeof TutorClaimsClaimIdRouteImport
      parentRoute: typeof TutorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminInstitutionsRoute: typeof AdminInstitutionsRoute
  AdminMessagingRoute: typeof AdminMessagingRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminInstitutionsRoute: AdminInstitutionsRoute,
  AdminMessagingRoute: AdminMessagingRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LecturerRouteRouteChildren {
  LecturerAnalyticsRoute: typeof LecturerAnalyticsRoute
  LecturerAttendanceRoute: typeof LecturerAttendanceRoute
  LecturerMessagesRoute: typeof LecturerMessagesRoute
  LecturerReportsRoute: typeof LecturerReportsRoute
  LecturerScheduleRoute: typeof LecturerScheduleRoute
  LecturerSessionsRoute: typeof LecturerSessionsRoute
  LecturerTutorsRoute: typeof LecturerTutorsRoute
  LecturerVerificationQueueRoute: typeof LecturerVerificationQueueRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
}

const LecturerRouteRouteChildren: LecturerRouteRouteChildren = {
  LecturerAnalyticsRoute: LecturerAnalyticsRoute,
  LecturerAttendanceRoute: LecturerAttendanceRoute,
  LecturerMessagesRoute: LecturerMessagesRoute,
  LecturerReportsRoute: LecturerReportsRoute,
  LecturerScheduleRoute: LecturerScheduleRoute,
  LecturerSessionsRoute: LecturerSessionsRoute,
  LecturerTutorsRoute: LecturerTutorsRoute,
  LecturerVerificationQueueRoute: LecturerVerificationQueueRoute,
  LecturerIndexRoute: LecturerIndexRoute,
}

const LecturerRouteRouteWithChildren = LecturerRouteRoute._addFileChildren(
  LecturerRouteRouteChildren,
)

interface TutorRouteRouteChildren {
  TutorHelpRoute: typeof TutorHelpRoute
  TutorMessagingRoute: typeof TutorMessagingRoute
  TutorNotesRoute: typeof TutorNotesRoute
  TutorRegisterGenerationRoute: typeof TutorRegisterGenerationRoute
  TutorSchedulesRoute: typeof TutorSchedulesRoute
  TutorSessionsRoute: typeof TutorSessionsRoute
  TutorIndexRoute: typeof TutorIndexRoute
  TutorClaimsClaimIdRoute: typeof TutorClaimsClaimIdRoute
  TutorClaimsIndexRoute: typeof TutorClaimsIndexRoute
}

const TutorRouteRouteChildren: TutorRouteRouteChildren = {
  TutorHelpRoute: TutorHelpRoute,
  TutorMessagingRoute: TutorMessagingRoute,
  TutorNotesRoute: TutorNotesRoute,
  TutorRegisterGenerationRoute: TutorRegisterGenerationRoute,
  TutorSchedulesRoute: TutorSchedulesRoute,
  TutorSessionsRoute: TutorSessionsRoute,
  TutorIndexRoute: TutorIndexRoute,
  TutorClaimsClaimIdRoute: TutorClaimsClaimIdRoute,
  TutorClaimsIndexRoute: TutorClaimsIndexRoute,
}

const TutorRouteRouteWithChildren = TutorRouteRoute._addFileChildren(
  TutorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LecturerRouteRoute: LecturerRouteRouteWithChildren,
  TutorRouteRoute: TutorRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  StudentCheckInRoute: StudentCheckInRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
